/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.UIManager;

/**
 *
 * @author Danny Jimenez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public static Principal principal = new Principal();
    private static VentanaAnalisis analisis = new VentanaAnalisis();
    private static VentanaSismos sismos = new VentanaSismos();
    private static VentanaNotificaciones notificaciones = new VentanaNotificaciones();
    
    public Principal() {
        super("Ventana principal");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        btnAnalisis = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        BtnSismos = new javax.swing.JButton();
        btnNotificaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        PanelPrincipal.setBackground(new java.awt.Color(240, 168, 96));

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Vista/Bundle"); // NOI18N
        Titulo.setText(bundle.getString("Principal.Titulo.text")); // NOI18N
        Titulo.setToolTipText(bundle.getString("Principal.Titulo.toolTipText")); // NOI18N

        btnAnalisis.setBackground(new java.awt.Color(248, 204, 87));
        btnAnalisis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnalisis.setForeground(new java.awt.Color(255, 255, 255));
        btnAnalisis.setText(bundle.getString("Principal.btnAnalisis.text")); // NOI18N
        btnAnalisis.setBorderPainted(false);
        btnAnalisis.setPreferredSize(null);
        btnAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisisActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(248, 204, 87));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText(bundle.getString("Principal.btnSalir.text")); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        BtnSismos.setBackground(new java.awt.Color(248, 204, 87));
        BtnSismos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnSismos.setForeground(new java.awt.Color(255, 255, 255));
        BtnSismos.setText(bundle.getString("Principal.BtnSismos.text")); // NOI18N
        BtnSismos.setBorderPainted(false);
        BtnSismos.setPreferredSize(null);
        BtnSismos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSismosActionPerformed(evt);
            }
        });

        btnNotificaciones.setBackground(new java.awt.Color(248, 204, 87));
        btnNotificaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNotificaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnNotificaciones.setText(bundle.getString("Principal.btnNotificaciones.text")); // NOI18N
        btnNotificaciones.setBorderPainted(false);
        btnNotificaciones.setPreferredSize(null);
        btnNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSismos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        PanelPrincipalLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnSismos, btnAnalisis, btnNotificaciones, btnSalir});

        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSismos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        PanelPrincipalLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnSismos, btnAnalisis, btnNotificaciones, btnSalir});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisActionPerformed
        principal.setVisible(false);
        analisis.setVisible(true);
    }//GEN-LAST:event_btnAnalisisActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void BtnSismosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSismosActionPerformed
        principal.setVisible(false);
        sismos.setVisible(true);
    }//GEN-LAST:event_BtnSismosActionPerformed

    private void btnNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionesActionPerformed
        principal.setVisible(false);
        notificaciones.setVisible(true);
    }//GEN-LAST:event_btnNotificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch(Exception e){
            System.out.println(e);
        }
        principal.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnSismos;
    public javax.swing.JPanel PanelPrincipal;
    public javax.swing.JLabel Titulo;
    public javax.swing.JButton btnAnalisis;
    public javax.swing.JButton btnNotificaciones;
    public javax.swing.JButton btnSalir;
    // End of variables declaration//GEN-END:variables
}
